---
mdd_tags:
  - router
mdd_checks:
  - name: Check Network-wide Routes
    command: 'show ip route'
    schema: 'pyats/show_ip_route.yml.j2'
    method: nso_parse
    check_vars:
      routes:
        - 172.16.0.0/16
        - 192.168.1.0/24
        - 192.168.2.0/24
