stages:
  - clean
  - build-cml
  - build-nso
  - validate
  - update
  - check

image: ghcr.io/model-driven-devops/mdd:latest

variables:
  ANSIBLE_CONFIG: "./ansible.cfg"
  CML_VERIFY_CERT: "false"

clean:
  stage: clean
  script:
    - ansible-playbook cisco.cml.clean
  only:
    changes:
      - files/arch3_csr.yaml.j2
  resource_group: mdd

build-cml:
  stage: build-cml
  script:
    - ansible-playbook cisco.cml.build -e startup='host' -e wait='yes'
  only:
    changes:
      - files/arch3_csr.yaml.j2
  resource_group: mdd

build-nso:
  stage: build-nso
  script:
    - ansible-playbook ciscops.mdd.nso_install
    - ansible-playbook ciscops.mdd.nso_update_packages
    - ansible-playbook ciscops.mdd.nso_init
    - ansible-playbook ciscops.mdd.nso_update_devices
  resource_group: mdd
  only:
    changes:
      - files/arch3_csr.yaml.j2

validate:
  stage: validate
  script:
    - ansible-playbook ciscops.mdd.validate
  resource_group: mdd

update:
  stage: update
  script:
    - ansible-playbook ciscops.mdd.nso_sync_from
    - ansible-playbook ciscops.mdd.update -e dry_run=no
  resource_group: mdd

check:
  stage: check
  script:
    - ansible-playbook ciscops.mdd.check
  resource_group: mdd
