collections:
  - name: https://github.com/model-driven-devops/ansible-mdd.git
    type: git
  - name: https://github.com/CiscoDevNet/ansible-cml.git
    type: git
  - name: ansible.netcommon
  - name: ansible.utils
  - name: community.yang
  - name: netbox.netbox
