collections:
  - name: cisco.cml
    version: 1.0.0
  - name: https://github.com/model-driven-devops/ansible-mdd.git,mdd-dev
    type: git
  - name: https://github.com/model-driven-devops/ansible-nso.git
    type: git
