all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - hq
      - site1
      - site2
    regions:
      - internet
      - org
      - region1
      - region2
  children:
    network:
      children:
        internet:
          children:
            internet_routers:
              hosts:
                internet-rtr1:
                  tags:
                    - router
                    - bgp
        org:
          children:
            region1:
              children:
                hq:
                  hosts:
                    hq-rtr1:
                      tags:
                        - router
                        - bgp
                    hq-rtr2:
                      tags:
                        - router
                        - bgp
                    hq-sw1:
                      tags:
                        - switch
                    hq-sw2:
                      tags:
                        - switch
                site1:
                  hosts:
                    site1-rtr1:
                      tags:
                        - router
                        - bgp
                    site1-sw1:
                      tags:
                        - switch
            region2:
              children:
                site2:
                  hosts:
                    site2-rtr1:
                      tags:
                        - router
                        - bgp
                    site2-sw1:
                      tags:
                        - switch
    switches:
      hosts:
        hq-sw1:
        hq-sw2:
        site1-sw1:
        site2-sw2:
    routers:
      hosts:
        hq-rtr1:
        hq-rtr2:
        site1-rtr1:
        site2-rtr2:
