all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
    sites:
      - hq
      - site1
      - site2
    regions:
      - internet
      - org
      - region1
      - region2
  children:
    internet_routers:
      hosts:
        internet-rtr1:
          tags:
            - router
            - bgp
    network:
      children:
        switches:
          hosts:
            hq-sw1:
            hq-sw2:
            site1-sw1:
            site2-sw1:
        routers:
          children:
            hq_routers:
              hosts:
                hq-rtr1:
                hq-rtr2:
            site_routers:
              hosts:
                site1-rtr1:
                site2-rtr1:      
    org:
      children:
        region1:
          children:
            hq:
              hosts:
                hq-rtr1:
                  tags:
                    - hq_router
                    - bgp
                    - ospf
                hq-rtr2:
                  tags:
                    - hq_router
                    - bgp
                    - ospf
                hq-sw1:
                  tags:
                    - switch
                hq-sw2:
                  tags:
                    - switch
            site1:
              hosts:
                site1-rtr1:
                  tags:
                    - site_router
                site1-sw1:
                  tags:
                    - switch
        region2:
          children:
            site2:
              hosts:
                site2-rtr1:
                  tags:
                    - site_router
                site2-sw1:
                  tags:
                    - switch

