ping_tests:
  #
  # Test branch-to-main
  #
  # - dst_ip: 172.16.0.100
  #   src_host: site1-rtr1
  #   pass: yes
  # - dst_ip: 172.16.0.100
  #   src_host: site2-rtr1
  #   pass: yes

  #
  # Test main-to-branch
  #
  # - dst_ip: 192.168.1.100
  #   src_host: hq-rtr1
  #   pass: yes
  # - dst_ip: 192.168.2.100
  #   src_host: hq-rtr1
  #   pass: yes

  #
  # Test internet-to-site
  #
  - dst_ip: 172.16.0.100
    src_host: internet-rtr1
    pass: yes
  - dst_ip: 192.168.1.100
    src_host: internet-rtr1
    pass: yes
  - dst_ip: 192.168.2.100
    src_host: internet-rtr1
    pass: yes

  #
  # Test offsite
  #
  - dst_ip: 8.8.8.8
    src_host: internet-rtr1
    pass: no
