---
name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'mdd-data/**.yml'
      - 'mdd-data/**.yaml'

env:
  CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
  CML_LAB: ${{ secrets.CML_LAB }}
  CML_USERNAME: ${{ secrets.CML_USERNAME }}
  CML_HOST: ${{ secrets.CML_HOST }}
  CML_VERIFY_CERT: ${{ secrets.CML_VERIFY_CERT }}
  ANSIBLE_PYTHON_INTERPRETER: /usr/local/bin/python

jobs:
  test:
    runs-on: self-hosted
    environment: mdd-dev
    concurrency: mdd-dev
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2
      - name: Run YAMLLINT
        run: yamllint mdd-data
      - name: Save Rollback
        run: ansible-playbook ciscops.mdd.nso_save_rollback
      - name: Validate Data
        run: ansible-playbook ciscops.mdd.validate
      - name: Deploy Changes
        run: ansible-playbook ciscops.mdd.nso_update_oc -e dry_run=no
      - name: Run Checks
        run: ansible-playbook ciscops.mdd.check
      - name: Load Rollback
        run: ansible-playbook ciscops.mdd.nso_load_rollback
