---
name: NSO Update Packages
on:
  workflow_dispatch:

env:
  CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
  CML_LAB: ${{ secrets.CML_LAB }}
  CML_USERNAME: ${{ secrets.CML_USERNAME }}
  CML_HOST: ${{ secrets.CML_HOST }}
  CML_VERIFY_CERT: ${{ secrets.CML_VERIFY_CERT }}
  ANSIBLE_PYTHON_INTERPRETER: /usr/local/bin/python

jobs:
  nso_update_packages:
    runs-on: self-hosted
    environment: mdd-dev
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2
      - name: NSO Check Sync
        run: ansible-playbook ciscops.mdd.nso_update_packages