---
name: Show OC Data
on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Limit Hosts'
        type: string 
        required: false
        default: 'all'

# env:
#   ANSIBLE_PYTHON_INTERPRETER: /usr/local/bin/python

jobs:
  show_oc:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/model-driven-devops/mdd:latest
    steps:
      - name: Checkout Inventory
        uses: actions/checkout@v2
      - name: Check
        run: ansible-playbook ciscops.mdd.show_oc --limit=${{ inputs.limit }}
